name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDro4M9bp/RfdN+JEVUxQDMKZ0E949xJjayoy5ysXyji4YaK7F64Gvbwp8t3CXkHbx/IGvG3wjDy82h1oOEQ83ByC7kkYTmGXBarZGPmmburYA2onzGzdNfJQTvghpuS+lzJOq9/Udx99m4PzMmHZs13BtjMgHbd2j8bxMR1w4xIZtzlD4hsYMp96bTgjViOR3IJo7PNZYB6Rh+h7PbPHhPiVw47QTY0mn40qv1OQO5qr3rLXb0d9PC/tpcVXyNj8HEibixmiVty6yhXgcbz932mn8MIVh9ikizk4WLJz+MeKcw+Bg0g0lhKfr4QorMA7pnHGSFSYN/cYSuBMsLEvLjXcHAY3F1vIJTFCmlvBRZHlxCP0lH3SJbNl+C8a1WWxw+egIessIIVriNo4tKfi0jw9XsdN1m7WUT++aFFdZh/tjWesYyVIub/4MvgWoNyNJggNyMR05Fc2D0g/oxdbHrO27R0bLnTcc0dZjBxbzPjpNj6TCClDDWSDR9XgUlHnejPMA2hduQKdlJoXmg81oZaHf8xmMJxVnM8AEi8GMWCPWk0eR9PBKMqjrDsSnzA7/ErfxkvdA//PVJNwMCXGT2YLvgce5uepclJF1PP5X0b8Po7+RylGP0JvBuZJMcGsvNh4LimxILTPYU4srMy5b23nUC4T3TK+T4CLEg6n30dQ== Praktikan1
            echo "Cek folder project";
            [ -d "${HOME}/senpro/498561/modul02/senpro-github-action/" ] && (
              echo "Repository sudah ada. Building...";
              cd ~/senpro/498561/modul02/senpro-github-action;
              git restore .;
              git pull origin main;
              echo "Install Package dan Build Project";
              npm install;
              npm run build;
            ) || (
              echo "Repository belum di-clone. Cloning...";
              mkdir -p ~/senpro/498561/modul02;
              cd ~/senpro/498561/modul02;
              git clone https://github.com/selvirasell/senpro-github-action.git;
              cd ~/senpro/498561/modul02/senpro-github-action;
              echo "Install Package dan Build Project";
              npm install;
              npm run build;
            )
